version: '3.8'

services:
  shareholder-web:
    build: .
    container_name: shareholder-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
